version: '3.3'
services: 
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-mysql-app
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    networks:
      - nodeserver
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password    
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    networks:
      - nodeserver

volumes: 
  db-config:
  db-data:

networks:
  nodeserver:
    external:
      name: nodeserver